  void (*resize)(UI *ui, Integer rows, Integer columns);
  void (*clear)(UI *ui);
  void (*eol_clear)(UI *ui);
  void (*cursor_goto)(UI *ui, Integer row, Integer col);
  void (*mode_info_set)(UI *ui, Boolean enabled, Array cursor_styles);
  void (*update_menu)(UI *ui);
  void (*busy_start)(UI *ui);
  void (*busy_stop)(UI *ui);
  void (*mouse_on)(UI *ui);
  void (*mouse_off)(UI *ui);
  void (*mode_change)(UI *ui, String mode, Integer mode_idx);
  void (*set_scroll_region)(UI *ui, Integer top, Integer bot, Integer left, Integer right);
  void (*scroll)(UI *ui, Integer count);
  void (*highlight_set)(UI *ui, HlAttrs attrs);
  void (*put)(UI *ui, String str);
  void (*bell)(UI *ui);
  void (*visual_bell)(UI *ui);
  void (*flush)(UI *ui);
  void (*update_fg)(UI *ui, Integer fg);
  void (*update_bg)(UI *ui, Integer bg);
  void (*update_sp)(UI *ui, Integer sp);
  void (*suspend)(UI *ui);
  void (*set_title)(UI *ui, String title);
  void (*set_icon)(UI *ui, String icon);
  void (*option_set)(UI *ui, String name, Object value);
